# Goal 2: Calculate $R_{net}$ & $\dot{q}_x$ *(No Water Layer)*

In [2]:
import sympy as sp
import numpy as np

In [73]:
T_oo = np.array([300, 305, 310, 315, 320, 325, 330]) # T_oo
# T_oo = sp.symbols('T_oo')
T_s = sp.symbols('T_s')

delta_T = T_s - T_oo
# delta_T = 30 # (Assume)

#T_f = (T_oo + T_s) / 2
T_f = 320
beta = 1/T_f

# cement=5cm, brick=10cm, lime=5cm
L = 2.5 # Independant of length
g = 9.8

# linear interpolation
# nu = 1e-6 * np.array([15.9, 16.4, 16.9, 17.4, 17.9, 18.4, 18.9])
# alpha = 1e-6 * np.array([22.50, 23.25, 24.0, 24.75, 25.50, 26.25, 27.00])
nu = 18e-6
alpha = 25e-6

Ra_L = (g * beta * delta_T * L**3) / (nu * alpha)
display(Ra_L)
# print('Raleigh Number =', Ra_L)

array([1063368055.55556*T_s - 319010416666.667,
       1063368055.55556*T_s - 324327256944.444,
       1063368055.55556*T_s - 329644097222.222,
       1063368055.55556*T_s - 334960937500.0,
       1063368055.55556*T_s - 340277777777.778,
       1063368055.55556*T_s - 345594618055.556,
       1063368055.55556*T_s - 350911458333.333], dtype=object)

In [74]:
Nu_L = 0.15 * Ra_L**(1/3)
display(Nu_L)
# print('Nusselt Number =', Nu_L)

array([1024.92687362504*(0.00333333333333333*T_s - 1)**0.333333333333333,
       1030.58956795435*(0.00327868852459016*T_s - 1)**0.333333333333333,
       1036.19070821137*(0.0032258064516129*T_s - 1)**0.333333333333333,
       1041.73194035413*(0.00317460317460317*T_s - 1)**0.333333333333333,
       1047.21484103001*(0.003125*T_s - 1)**0.333333333333333,
       1052.64092152652*(0.00307692307692308*T_s - 1)**0.333333333333333,
       1058.01163143999*(0.00303030303030303*T_s - 1)**0.333333333333333],
      dtype=object)

In [75]:
k = 27.7e-3
h_t = k/L * Nu_L

q_conv = h_t * delta_T # W/m^2
display(q_conv)

array([11.3561897597655*(0.00333333333333333*T_s - 1)**0.333333333333333*(T_s - 300),
       11.4189324129342*(0.00327868852459016*T_s - 1)**0.333333333333333*(T_s - 305),
       11.4809930469819*(0.0032258064516129*T_s - 1)**0.333333333333333*(T_s - 310),
       11.5423898991238*(0.00317460317460317*T_s - 1)**0.333333333333333*(T_s - 315),
       11.6031404386125*(0.003125*T_s - 1)**0.333333333333333*(T_s - 320),
       11.6632614105139*(0.00307692307692308*T_s - 1)**0.333333333333333*(T_s - 325),
       11.7227688763551*(0.00303030303030303*T_s - 1)**0.333333333333333*(T_s - 330)],
      dtype=object)

In [77]:
sigma = 5.67e-8 # Stefan Boltzmann Constant
epsilon = 0.85 # Absorbtivity of concrete
E_b = sigma * T_oo**4 # W/m^2

q_rad = E_b * epsilon / (1-epsilon) # W/m^2
display(q_rad)

array([-157.41598441,   20.4719614 ,  207.32698859,  403.4454964 ,
        609.12870359, -555.2903438 , -329.55480361])

In [78]:
q_net = q_rad + q_conv # W/m^2
display(q_net)

array([11.3561897597655*(0.00333333333333333*T_s - 1)**0.333333333333333*(T_s - 300) - 157.4159844096,
       11.4189324129342*(0.00327868852459016*T_s - 1)**0.333333333333333*(T_s - 305) + 20.4719614029,
       11.4809930469819*(0.0032258064516129*T_s - 1)**0.333333333333333*(T_s - 310) + 207.3269885904,
       11.5423898991238*(0.00317460317460317*T_s - 1)**0.333333333333333*(T_s - 315) + 403.4454964029,
       11.6031404386125*(0.003125*T_s - 1)**0.333333333333333*(T_s - 320) + 609.1287035904,
       11.6632614105139*(0.00307692307692308*T_s - 1)**0.333333333333333*(T_s - 325) - 555.2903438019,
       11.7227688763551*(0.00303030303030303*T_s - 1)**0.333333333333333*(T_s - 330) - 329.5548036144],
      dtype=object)

In [79]:
h_inside = 8.4 # W / (m^2 K)

k_1 = 0.72 # Concrete
k_2 = 0.71 # Brick
k_3 = 0.731 # Lime

L_1 = 0.05 # Concrete
L_2 = 0.1 # Brick
L_3 = 0.05 # Lime

R = 1/h_inside + L_1/k_1 + L_2/k_2 + L_3/k_3 # K/W

print(f"Net Resistance = {round(R, 3)} m^2*K/W")

Net Resistance = 0.398 m^2*K/W


In [82]:
T_inside = 300 # K, Constant temperature room 

# q_net = (T_s - T_inside) / R
# q_net - (T_s - T_inside) / R = 0
final_eqn = q_net - (T_s-T_inside)/R
display(final_eqn[0])

-2.51422683603044*T_s + 11.3561897597655*(0.00333333333333333*T_s - 1)**0.333333333333333*(T_s - 300) + 596.852066399533

In [110]:
n = len(final_eqn)
for i in range(n):
    display(sp.solve(final_eqn[i], T_s))

[344.824776346579]

[304.883193231439 - 5.27924392834988*I, 304.883193231439 + 5.27924392834988*I]

[289.685287978922 - 37.3029340997507*I, 289.685287978922 + 37.3029340997507*I]

[]

[269.327635783036 - 77.8473387883481*I, 269.327635783036 + 77.8473387883481*I]

[435.074290577927]

[412.929460187810]

References: Incorpera  
eqns: pg 611, table 995