# (Attempt 3) Goal 2: No Water Layer

In [1]:
import sympy as sp
import numpy as np

## **Initialize Values**

### Outside Air:

In [2]:
T_oo = np.array([300.0, 305.0, 310.0, 315.0, 320.0, 325.0, 330.0]) # T_oo
T_s = sp.symbols('T_s')

delta_T = T_s - T_oo

#T_f = (T_oo + T_s) / 2
T_f = 320.0
beta = 1/T_f

L = 2.5 # Independant of length
g = 9.8

nu = 18e-6
alpha = 25e-6

Ra_L = (g * beta * delta_T * L**3) / (nu * alpha)
display(Ra_L)
# print('Raleigh Number =', Ra_L)

array([1063368055.55556*T_s - 319010416666.667,
       1063368055.55556*T_s - 324327256944.444,
       1063368055.55556*T_s - 329644097222.222,
       1063368055.55556*T_s - 334960937500.0,
       1063368055.55556*T_s - 340277777777.778,
       1063368055.55556*T_s - 345594618055.556,
       1063368055.55556*T_s - 350911458333.333], dtype=object)

### Roof layers:

In [5]:
k_1 = 0.72 # Concrete
k_2 = 0.71 # Brick
k_3 = 0.73 # Lime

L_1 = 0.05 # Concrete
L_2 = 0.10 # Brick
L_3 = 0.05 # Lime

In [3]:
Nu_L = 0.15 * Ra_L**(1/3)
display(Nu_L)
# print('Nusselt Number =', Nu_L)

array([1024.92687362504*(0.00333333333333333*T_s - 1)**0.333333333333333,
       1030.58956795435*(0.00327868852459016*T_s - 1)**0.333333333333333,
       1036.19070821137*(0.0032258064516129*T_s - 1)**0.333333333333333,
       1041.73194035413*(0.00317460317460317*T_s - 1)**0.333333333333333,
       1047.21484103001*(0.003125*T_s - 1)**0.333333333333333,
       1052.64092152652*(0.00307692307692308*T_s - 1)**0.333333333333333,
       1058.01163143999*(0.00303030303030303*T_s - 1)**0.333333333333333],
      dtype=object)

In [4]:
k = 27.7e-3
h_t = k/L * Nu_L

q_conv = h_t * delta_T # W / m^2
display(q_conv)

array([11.3561897597655*(0.00333333333333333*T_s - 1)**0.333333333333333*(T_s - 300.0),
       11.4189324129342*(0.00327868852459016*T_s - 1)**0.333333333333333*(T_s - 305.0),
       11.4809930469819*(0.0032258064516129*T_s - 1)**0.333333333333333*(T_s - 310.0),
       11.5423898991238*(0.00317460317460317*T_s - 1)**0.333333333333333*(T_s - 315.0),
       11.6031404386125*(0.003125*T_s - 1)**0.333333333333333*(T_s - 320.0),
       11.6632614105139*(0.00307692307692308*T_s - 1)**0.333333333333333*(T_s - 325.0),
       11.7227688763551*(0.00303030303030303*T_s - 1)**0.333333333333333*(T_s - 330.0)],
      dtype=object)

In [5]:
sigma = 5.67e-8 # Stefan Boltzmann Constant
epsilon = 0.85 # Absorbtivity of concrete
E_b = sigma * T_oo**4 # W/m^2

q_rad = E_b * epsilon / (1-epsilon) # W/m^2
display(q_rad)

array([2602.53      , 2780.41794581, 2967.272973  , 3163.39148081,
       3369.074688  , 3584.62863281, 3810.364173  ])

In [6]:
q_net = q_rad + q_conv # W/m^2
display(q_net)

array([11.3561897597655*(0.00333333333333333*T_s - 1)**0.333333333333333*(T_s - 300.0) + 2602.53,
       11.4189324129342*(0.00327868852459016*T_s - 1)**0.333333333333333*(T_s - 305.0) + 2780.4179458125,
       11.4809930469819*(0.0032258064516129*T_s - 1)**0.333333333333333*(T_s - 310.0) + 2967.272973,
       11.5423898991238*(0.00317460317460317*T_s - 1)**0.333333333333333*(T_s - 315.0) + 3163.3914808125,
       11.6031404386125*(0.003125*T_s - 1)**0.333333333333333*(T_s - 320.0) + 3369.074688,
       11.6632614105139*(0.00307692307692308*T_s - 1)**0.333333333333333*(T_s - 325.0) + 3584.6286328125,
       11.7227688763551*(0.00303030303030303*T_s - 1)**0.333333333333333*(T_s - 330.0) + 3810.364173],
      dtype=object)

In [7]:
R = 1/h_r + L_1/k_1 + L_2/k_2 + L_3/k_3 # K/W

print(f"Net Resistance = {round(R, 3)} m^2*K/W")

Net Resistance = 0.398 m^2*K/W


In [8]:
T_r = 300 # K, Constant temperature room 

# q_net = (T_s - T_r) / R
# q_net - (T_s - T_r) / R = 0
final_eqn = q_net - (T_s-T_r)/R
display(final_eqn[0])

-2.51363467968919*T_s + 11.3561897597655*(0.00333333333333333*T_s - 1)**0.333333333333333*(T_s - 300.0) + 3356.62040390676

In [9]:
n = len(final_eqn)
for i in range(n):
    display(sp.solve(final_eqn[i], T_s))

[132.093479425268 - 221.349316461391*I, 132.093479425268 + 221.349316461391*I]

[128.969059542158 - 230.976564098072*I, 128.969059542158 + 230.976564098072*I]

[]

[121.778583394725 - 251.266583754658*I, 121.778583394725 + 251.266583754658*I]

[117.704400726045 - 261.936533418232*I, 117.704400726045 + 261.936533418232*I]

[113.305452677038 - 272.961334768938*I, 113.305452677038 + 272.961334768938*I]

[]

References: Incorpera  
eqns: pg 611, table 995